### ISSUE TITLE
can't get current user id from MainActivity

### ISSUE THREAD

**Issue by TakwaYousfi** [strongloop/loopback-sdk-android#102]
I am using loopback-sdk-android for my app, I login the user successfully, and I can access the token and the user object in the LoginActivity. But when i try to get the current user id from the following activities (MainActivity or other) it always returns null! 
Official documentation says the SDK is supposed to automatically save these in SharedPreferences, put how can I access them from other activities?

**Comment by Soufien** [comment]
You should maintain the same contexte for your RestAdapter and make your CustomUser Repository a singleton where you will use it all the long your application life : 
Example : 

- How to give the RestAdapter the same contexte all the long you application life :
[https://gist.github.com/Soufien/52c1d42399d1e013d02e84efd0c6c8fa](MyApplication.java)

- And how to make you Custom user repository a singleton : 
[https://gist.github.com/Soufien/a45bd9a4734076b37c094eb4d3827161](UtilisateurRepository.java)
