### ISSUE TITLE
Adding     compile 'com.strongloop:loopback-android:1.+'  creates error

### ISSUE THREAD

**Issue by stephanemaarek** [strongloop/loopback-sdk-android#40]
Adding     compile 'com.strongloop:loopback-android:1.+' 
as a dependency creates an error on my gradle:

Error:Module version com.loopj.android:android-async-http:1.4.3 depends on libraries but is not a library itself

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can reproduce it using the latest version.

**Comment by bajtos** [comment]
Possibly related: #55
