### ISSUE TITLE
Describe how to invoke a custom method, include an example

### ISSUE THREAD

**Issue by jshohel** [strongloop/loopback-sdk-android#53]
It will be nice to have a more explaination of "how to invoke a custom method from Android". Explaining what is happening on each line for better understanding.

Also, it will be really helpful if runnable runtrip example is added with other examples.

NOTE: By round trip i mean "Android---> Loopback --->Android" trip.

The history of creating this issue can be found here -

http://stackoverflow.com/questions/27087760/loopback-custom-method-call-from-android/27126976?noredirect=1#comment42785947_27126976

**Comment by Sequoia** [comment]
@bajtos is there an Android Champion who can document this? If not, recommend this be closed `wontfix`.

**Comment by bajtos** [comment]
@loay and @superkhau are the owners of the Android SDK. Honestly, since this was not a priority for us in the last two years, I doubt it will get into a sprint backlog anytime soon. Let's close the issue for now.
