### ISSUE TITLE
Fix docs for UserRepository

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-sdk-android#58]
See the following mailing-list thread:

https://groups.google.com/forum/#!topic/loopbackjs/euQYRSn-KbY

It is not possible to use `UserRepository<User>` directly, users always have to create a subclass.

**Comment by crandmck** [comment]
Updated http://docs.strongloop.com/display/LB/Android+SDK#AndroidSDK-Usersandauthentication
@bajtos PTAL.

**Comment by bajtos** [comment]
LGTM.
