### ISSUE TITLE
No peer certificate error while connection to https

### ISSUE THREAD

**Issue by newaz** [strongloop/loopback-sdk-android#64]
Hi,
I have configured my loopback app with ssl (https://github.com/strongloop/loopback-example-ssl)

Now, when I try to access any api from android, it gives me the following error. 

```java
E/Probe-RegistrationThread(11512): Failed to get remote installation id: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
D/Probe-MainActivity(11512): InstallationCompleteReceiver called
```

any idea on how can solve this?

**Comment by newaz** [comment]
Hi, Can anyone help me in this please ?

**Comment by bajtos** [comment]
This is what the documentation says about `SSLPeerUnverifiedException`:

> When the peer was not able to identify itself (for example; no certificate, the particular cipher suite being used does not support authentication, or no peer authentication was established during SSL handshaking) this exception is thrown.

Can you access your SSL server from the browser? Will the browser happily accept the server certificate, or show any warnings?

See also this StackOverflow answer: http://stackoverflow.com/a/18210464/69868

**Comment by newaz** [comment]
Hi, I noticed that the SSL certificate that was (from my client) given to me is not certified by any root certification provider. That is why when in browser I go to browse it, it says "Not trusted" and then I need to add exception to make it work. So the handshake or validation is done manually to make it work in browser.

Does Android SSL client need a valid certificate which is certified by one root provider where no "Add exception" is needed ?  Like if you use paypal  it is certified by a root provider so no Add Exception needed.

**Comment by bajtos** [comment]
> Does Android SSL client need a valid certificate which is certified by one root provider where no "Add exception" is needed ? Like if you use paypal it is certified by a root provider so no Add Exception needed.

Yes, exactly.

However, there should be a way how to configure the runtime to accept invalid certificates too. I am not familiar with Java and Android enough to give you the solution right off top of my head, use Google and/or search StackOverflow for that.

**Comment by newaz** [comment]
Hi,
I have a valid certificate now. I have tested in my pc brower and also in my android browser. it went normally without any exception. But from android client when I try to connect with my server, it gives me the same error :(

Can it be a SNI support problem? Since I have read that loopj async http lib does not use SNI.

**Comment by bajtos** [comment]
> Can it be a SNI support problem? Since I have read that loopj async http lib does not use SNI.

Yes, that's very likely.
