### ISSUE TITLE
How to use the url parameter of loopback.File?

### ISSUE THREAD

**Issue by hideya** [strongloop/loopback-sdk-android#80]
Could someone tell me what is the intended use of the url parameter of loopback.File?
https://github.com/strongloop/loopback-sdk-android/blob/master/src/main/java/com/strongloop/android/loopback/File.java#L25-L34

Maybe I'm missing something but I don't think it is set by anyone.  I don't find any code that sets `url` nor calls `setUrl()`.  Its public setter also makes me wonder the intended usage...

**Comment by bajtos** [comment]
@hideya I believe this property is set from the JSON response returned by the server, e.g. when calling `fileRepository.upload()`. I believe this url can be used to access the file directly, for example via `<img src="file.url">`.
